version: 2.0
jobs:
  build:
    docker:
      - image: fsharp
    steps:
      - checkout
      - run:
          name: Restore Packages
          command:
            dotnet restore CafeApp.sln
      - run:
          name: Build
          command:
            ./build.sh BuildTests
      - run:
          name: Run Tests
          command:
            ./build.sh RunUnitTests