version: 2.0
jobs:
  build:
    docker:
      - image: fsharp:10.2-netcore
    steps:
      - checkout
      - run:
          name: Check dir
          command: pwd
      - run:
          name: See dir content
          command: ls -al
      - run:
          name: Check dotnet installation
          command: dotnet --version
      - run:
          name: Check mono installation
          command: mono --version
      - run:
          name: Install fake
          command: dotnet tool install fake-cli -g
      - run:
          name: Add fake to PATH
          command: export PATH="$PATH:/root/.dotnet/tools"
      - run:
          name: Check Fake Version
          command: fake --version
      - run:
          name: Run Tests
          command:
            ./build.sh
