version: 2.0
jobs:
  build:
    docker:
      - image: fsharp:10.2.3-netcore
    steps:
      - checkout
      - run:
          name: Check dir
          command: pwd
      - run:
          name: See dir content
          command: ls -al
      - run:
          name: Check dotnet installation
          command: dotnet --version
      - run:
          name: Check mono installation
          command: mono --version
      - run:
          name: Restore Packages
          command:
            dotnet restore
      - run:
          name: Build
          command:
            ./build.sh BuildTests
      - run:
          name: Run Tests
          command:
            ./build.sh RunUnitTests