version: 2.0
jobs:
  build:
    docker:
      - image: fsharp:10.2-netcore
    environment:
      BASH_ENV: /root/.bashrc
    steps:
      - checkout
      - run:
          name: Check dir
          command: pwd
      - run:
          name: See dir content
          command: ls -al
      - run:
          name: Check dotnet installation
          command: dotnet --version
      - run:
          name: Check mono installation
          command: mono --version
      - run:
          name: Install fake
          command: dotnet tool install fake-cli -g
      - run:
          name: Add fake to path
          command: echo 'export PATH=/root/.dotnet/tools:$PATH' >> $BASH_ENV
      - run:
          name: Check Fake Version
          command: fake --version
      - run:
          name: Run Tests
          command:
            ./build.sh
